---
# ServiceAccount for Vote Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vote
  namespace: default
  labels:
    app: vote

---
# ServiceAccount for Result Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: result
  namespace: default
  labels:
    app: result

---
# ServiceAccount for Worker Service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: worker
  namespace: default
  labels:
    app: worker

---
# ServiceAccount for Database
apiVersion: v1
kind: ServiceAccount
metadata:
  name: db
  namespace: default
  labels:
    app: db

---
# ServiceAccount for Redis
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: default
  labels:
    app: redis
